In [4]:
# Lesson: NumPy 초급 튜토리얼

# NumPy 가져오기
import numpy as np

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
# NumPy 배열 생성하기
""" 
Array는 리스트다.
리스트는 = [1, "apple", True]

수학에서 벡터는 크기와 방향을 개념
화살표의 길이는 : 크기를 나타내고
화살표의 방향은 : 방향을 나타내고
크기와 방향을 일정한 값으로 지정해두고 다른 벡터들과 연산했을때 그 값들 사이의 특징과 개념들을
수학적으로 풀 수 있다.

세상의 있는 지식들을 수학적으로 풀어야 할때 가장 대표적으로 사용되는 수학개념이 바로 선형대수입니다.
스칼라, 벡터, 매트릭스, 텐서 ......
(숫자), (숫자 여러개), (벡터가 여러개면 매트릭스), (매트릭스가 여러개면 텐서)
"""

arr1 = np.array([1, 2, 3, 4, 5]) # 1 dimension 
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]]) # two dimension

# 배열 요소 접근하기

print("arr1의 첫 번째 요소:", arr1[2])
print("arr2의 1행 2열 요소:", arr2[1, 2])

arr1의 첫 번째 요소: 3
arr2의 1행 2열 요소: 6


In [ ]:
"""
이미지
정사각형인 형태가 많음
가로, 세로, 그 안에 그림이 있음
가로는 100cm, 세로도 100cm, 그림은 강아지

가로축에 1cm당 1개 픽셀이라하면은 가로축에는 값이 100개가 있죠
세로축도 같은 조건이라면 당연히 100개

width = [3,51,6,1,7,1,5,2,6,........]
height = [3,51,6,1,7,1,5,2,6,........]
색깔은 0~255
pixcel = [35, 108, 40, 20, 50 ............. 10000]
그림은?? 검은색(눈), 코는(흰색), 입은(빨간색) 배경은 풀밭(초록색)



""" 

In [8]:
# 배열 속성
print("arr1의 형태:", arr1.shape)
print("arr2의 형태:", arr2.shape)
print("arr1의 데이터 타입:", arr1.dtype)
print("arr2의 데이터 타입:", arr2.dtype)

arr1의 형태: (5,)
arr2의 형태: (3, 3)
arr1의 데이터 타입: int64
arr2의 데이터 타입: int64


In [9]:
new_arr = np.array([1.1, 0.3, 0.5, 0.4])
new_arr

array([1.1, 0.3, 0.5, 0.4])

In [10]:
new_arr.dtype

dtype('float64')

In [11]:
# 배열 연산
arr3 = arr1 + 2
arr4 = arr1 * 3

print("arr3:", arr3)
print("arr4:", arr4)

arr3: [3 4 5 6 7]
arr4: [ 3  6  9 12 15]


In [12]:
# 배열 함수
print("arr1의 합계:", np.sum(arr1))
print("arr2의 평균:", np.mean(arr2))
print("arr1의 최댓값:", np.max(arr1))
print("arr2의 최솟값:", np.min(arr2))

arr1의 합계: 15
arr2의 평균: 5.0
arr1의 최댓값: 5
arr2의 최솟값: 1


In [18]:
# 배열 재구성
arr5 = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr5.reshape(2, 3)
print("재구성된 배열:", reshaped_arr)

재구성된 배열: [[1 2 3]
 [4 5 6]]


In [19]:
# 배열 슬라이싱
arr6 = np.array([1, 2, 3, 4, 5])
sliced_arr = arr6[1:4]
print("슬라이싱된 배열:", sliced_arr)

슬라이싱된 배열: [2 3 4]


In [21]:
num_list1 = [1,2,3]
num_list2 = [4,5,6]
num_list3 = num_list1 + num_list2
num_list3

[1, 2, 3, 4, 5, 6]

In [22]:
num_list3 = np.array(num_list3)
num_list3

array([1, 2, 3, 4, 5, 6])

In [23]:
num_sum = np.sum(num_list3)
num_sum

21

In [25]:
# 배열 연결
arr7 = np.array([1, 2, 3])
arr9 = np.array([4, 5, 6])

concatenated_arr = np.concatenate((arr7, arr9))
print("연결된 배열:", concatenated_arr)

연결된 배열: [1 2 3 4 5 6]


In [26]:
# 배열 스택
stacked_arr = np.stack((arr7, arr9))
print("스택된 배열:", stacked_arr)

# 난수 생성
random_arr = np.random.rand(3, 2)
print("난수 배열:", random_arr)

스택된 배열: [[1 2 3]
 [4 5 6]]
난수 배열: [[0.19039737 0.59060911]
 [0.03878429 0.54749276]
 [0.97100062 0.00983348]]
